### ISSUE TITLE
Create Secured Build Runner

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/open-source-programs#87]
Decision point: start with secured, self-hosted GitHub build runners on our AWS infra.

We’ll have to ensure we don’t allow [arbitrary remote execution](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security) by community members, by ensuring that only TBD employees may execute within our secured environment. Community may run pipelines on standard GitHub runners.

**Comment by ALRubinger** [comment]
@leordev - cool to share the @alec-brooks update we discussed internally here as a comment?

**Comment by alec-brooks** [comment]
Hey, I have a proof of concept working at the moment, where a single public repo is being periodically mirrored internally, once it is mirrored in it then gets configured to have the builds run on our self hosted runners. Now it should be a matter of getting the actions working when using the self hosted runners and then rolling that out across more of the public repos.

**Comment by ALRubinger** [comment]
Awesome @alec-brooks - is the next step then to me and @leordev to update the Actions on the internal mirror to trial this out?

Internal mirror, accessible to TBD employees only: https://github.com/tbdeng/tbdex-js-mirror

**Comment by alec-brooks** [comment]
I set it up so that when the mirroring is performed, an additional commit is added to change the runners being used. 

However, I have noticed today that the actions are triggered for each new commit being pushed to the mirrored repository. So the builds will run on GH runners as well as our self hosted once when we perform the mirroring. If that isn't a big deal we can leave things the way they are, but it does make the Action log a bit noisy.

Otherwise, I have just experimented with rolling the whole repository into a single commit, with the runners changed, which circumvents the issue of running the build more than is required, at the cost of the mirror no longer having the history.

Either approach should work, I don't have a huge preference for one over the other.

**Comment by ALRubinger** [comment]
Determined that for now we are going to pull this off scope and move ahead with locked versions of OS, NPM, Maven, Java etc in the public build runners. This decreases scope by our not needing #77 for the time being as well, and pulls up the near-term deliverable for artifact publishing. Agreed with @leordev and @alec-brooks.

**Comment by ALRubinger** [comment]
Reopening to use in future Milestone if necessary.

**Comment by ALRubinger** [comment]
Closing until we decide this is necessary
